name: Deploy Cloud Functions
on:
  push:
    branches:
      - development
jobs:
  qabuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
      - name: Export static files
        run: npm run export
      - name: Add .nojekyll file
        run: touch ./out/.nojekyll
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          branch: gh-pages
          folder: out
          args: deploy --only hosting:heartfulnesstestingapp               
        env:        
          PROJECT_ID: rameshtest-f25de
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}