# This is a basic workflow to help you get started with Actions

name: staging_deployment

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "development" ]
  pull_request:
    branches: [ "development" ]
    
  repository_dispatch:
    types: staging_deployment

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  qabuild:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js 16.15.1
        uses: actions/setup-node@v1
        with:
          node-version: 16.15.1
      - name: npm install
        run: npm install
      - name: npm run build
        run: npm run build
        env:
          FIREBASE_SERVICE_ACCOUNT_DETAILS: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}  
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:heartfulnesstestingapp     
        env:        
          PROJECT_ID: rameshtest-f25de
          GCP_SA_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}